# This workflow will build wheel files and upload them to GitHub Release assets.
# For information on uploading release asset, see: https://github.com/softprops/action-gh-release

name: Release

on:
  release:
    types: [published]
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build wheel
        run: python -m build
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: release
          token: ${{ secrets.GITHUB_TOKEN }}
